[package]
name = "rusty-time"
version = "0.1.0"
authors = ["Dhruv Jauhar <dhruv.jauhar@databricks.com>"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
